/*
 * Shadr
 *
 * Copyright © 2026 theDevJade. All rights reserved.
 *
 * Part of the Shadr project.
 * See LICENSE for licensing and distribution terms.
 */
package dev.shadr.core.shader

object GlslComposer {

    const val POSITION_ALPHA = 0xFB
    const val GRID = 16

    private val STAGE_INPUTS = """
        |in vec3 shadrWorldPos;
        |flat in vec3 shadrEye;
        |
        |vec3 shadrQuadCentre;
        |vec3 shadrQuadRight;
        |vec3 shadrQuadUp;
    """.trimMargin()

    private val TIME_HELPER = """
        |float shadr_time() { return GameTime * SHADR_CYCLE; }
    """.trimMargin()

    fun compose(registry: ShaderRegistry): String = buildString {
        appendLine("// Generated by GlslComposer. Do not edit")
        appendLine()
        appendLine("#define SHADR_POSITION_ALPHA $POSITION_ALPHA")
        appendLine("#define SHADR_SHADER_GRID $GRID")
        appendLine("#define SHADR_MARKER_R ${ShaderDef.MARKER_R}")
        appendLine("#define SHADR_MARKER_G ${ShaderDef.MARKER_G}")
        appendLine("#define SHADR_MARKER_A ${ShaderDef.MARKER_A}")
        appendLine()
        appendLine(STAGE_INPUTS)
        appendLine()
        appendLine(GlslHelpers.SOURCE)
        appendLine()
        appendLine(TIME_HELPER)
        appendLine()

        for (shader in registry.shaders) {
            appendLine("// ---- ${shader.id} " + "-".repeat(maxOf(0, 60 - shader.id.length)))
            appendLine(body(shader, registry))
            for (macro in GlslSymbols.macros(shader.source)) appendLine("#undef $macro")
            appendLine()
        }

        appendLine(dispatch(registry))
    }

    private fun body(shader: ShaderDef, registry: ShaderRegistry): String {
        if (shader.id in registry.conflicted) {
            val taken = registry.conflicts.filterValues { it.contains(shader.id) && it.first() != shader.id }
            return """
                |${taken.entries.joinToString("\n") { "//   ${it.key}: first defined by '${it.value.first()}'" }}
                |vec4 ${entry(shader)}(vec2 uv, float time, vec4 tint) { return vec4(0.0); }
            """.trimMargin()
        }

        val problems = GlslValidator.validate(shader)
        if (problems.any { it.fatal }) {
            return """
                |${problems.joinToString("\n") { "//   ${it.line}: ${it.message}" }}
                |vec4 ${entry(shader)}(vec2 uv, float time, vec4 tint) { return vec4(0.0); }
            """.trimMargin()
        }
        return shader.source.replace(
            Regex("""\bvec4\s+${ShaderDef.ENTRY_POINT}\s*\("""),
            "vec4 ${entry(shader)}(",
        )
    }

    private fun entry(shader: ShaderDef) = "${ShaderDef.ENTRY_POINT}_${shader.index}"

    private fun dispatch(registry: ShaderRegistry): String = buildString {
        appendLine("/** The marker for custom rendering */")
        appendLine("vec4 shadr_dispatch(int index, vec2 uv, float time, vec4 tint) {")
        appendLine("    switch (index) {")
        for (shader in registry.shaders) {
            appendLine("        case ${shader.index}: return ${entry(shader)}(uv, time, tint);")
        }
        appendLine("        default: return vec4(0.0);")
        appendLine("    }")
        appendLine("}")
    }

    fun previewParts(): Pair<String, String> {
        val marker = "\u0000"
        val (program, _) = previewProgram(marker)
        val at = program.indexOf(marker)
        return program.substring(0, at - 1) to program.substring(at + 2)
    }

    fun previewProgram(source: String): Pair<String, Int> {
        val preamble = """
            |#version 300 es
            |precision highp float;
            |
            |uniform vec2 uResolution;
            |uniform float uTime;
            |uniform vec4 uTint;
            |out vec4 fragColor;
            |
            |vec3 shadrWorldPos;
            |vec3 shadrEye;
            |vec3 shadrQuadCentre;
            |vec3 shadrQuadRight;
            |vec3 shadrQuadUp;
            |
            |${GlslHelpers.SOURCE}
        """.trimMargin()

        val epilogue = """
            |
            |void main() {
            |    vec2 uv = gl_FragCoord.xy / uResolution;
            |    uv.y = 1.0 - uv.y;
            |    shadrWorldPos = vec3(uv - 0.5, 0.0);
            |    shadrEye = vec3(0.0, 0.0, -2.0);
            |    shadrQuadCentre = vec3(0.0);
            |    shadrQuadRight = vec3(1.0, 0.0, 0.0);
            |    shadrQuadUp = vec3(0.0, 1.0, 0.0);
            |    fragColor = ${ShaderDef.ENTRY_POINT}(uv, mod(uTime, SHADR_CYCLE), uTint);
            |}
        """.trimMargin()

        return "$preamble\n$source\n$epilogue" to (preamble.lines().size + 1)
    }
}
