name: shadr_editor
description: "Editor UI for shadr."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  web_socket_channel: ^3.0.1

  cupertino_icons: ^1.0.8
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: JetBrainsMono Nerd Font Mono
      fonts:
        - asset: assets/fonts/jetbrains_mono_nerd.ttf
        - asset: assets/fonts/jetbrains_mono_nerd_semibold.ttf
          weight: 600