# Which vanilla programs shadr overrides. Written by the editor.
sky=true
clouds=true
celestials=false
blur=true
video=true
grading=true
grading.exposure=-0.05
grading.contrast=1.06
grading.tonemap=2
grading.saturation=0.94
grading.temperature=-24
grading.shadows=7897230
grading.vignette=0.45
grading.grain=0.18
grading.sharpen=0.2
bloom=true
godrays=true
ssao=true
ssr=true
water=true
fog=true
fog.density=5.0E-4
fog.color=16711680
